### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by jerimkaura** [geoffrey45/vaccines-api#1]
Good work bro. How do you return your responses in multiple languages?

**Comment by cwilvx** [comment]
Hello @jerimkaura

This is a mock API which will be used in a friend's final year android project. Since this is a very lightweight api, I don't think we'll be having localization features. The data will be hard-coded in a json file in the `/data` folder.

If you want to add localization features, you can fork the repo and maintain it. You can even open a pr if you want.

Thank you.

**Comment by jerimkaura** [comment]
<img width="1440" alt="Screenshot 2023-02-27 at 09 35 49" src="https://user-images.githubusercontent.com/50904889/221491784-b8b87977-cc76-4dcc-bb3d-0e83a29f85d1.png">



<img width="1440" alt="Screenshot 2023-02-27 at 09 36 23" src="https://user-images.githubusercontent.com/50904889/221491866-bb04b37a-6176-4c96-b8a1-298367b32bf3.png">

**Comment by jerimkaura** [comment]
The API is translated. How did you guys do this?

**Comment by cwilvx** [comment]
@jerimkaura  I have not implemented any translation features on the API side. I think the translation are done by your browser using the Google translate extension. 

![image](https://user-images.githubusercontent.com/48554537/221674409-9b72b86b-4249-489d-8e70-43dda292dfc0.png)
